# -*- coding: utf-8 -*-
"""DCA_vs_LumpSum_Crisis_Backtester

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJz-_z3-zJ3x1x2rxi6f8ld4vnP_FtLj
"""

# -*- coding: utf-8 -*-

import subprocess
import sys

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "yfinance", "plotly", "pandas", "numpy", "scipy"],
    check=True,
)

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import yfinance as yf

from scipy.optimize import brentq


SCENARIOS = [
    {
        "label": "2007-2012 Crash and Recovery",
        "ticker": "SPY",
        "start": "2007-10-01",
        "end": "2012-10-01",
    },
    {
        "label": "2015-2019 Bull Market",
        "ticker": "SPY",
        "start": "2015-01-01",
        "end": "2020-01-01",
    },
]


INITIAL_INVESTMENT = 10_000.0
N_MONTHS = 60


def fetch_price_data(ticker, start, end):
    raw = yf.download(
        ticker,
        start=start,
        end=end,
        auto_adjust=True,
        progress=False,
    )

    if raw.empty:
        raise RuntimeError(
            f"No data returned for {ticker} "
            f"from {start} to {end}."
        )

    close = raw["Close"]

    if isinstance(close, pd.DataFrame):
        close = close.iloc[:, 0]

    close = close.dropna().astype(float)
    close = close.to_frame(name="Close")

    if len(close) < 2:
        raise RuntimeError("Not enough price observations.")

    return close


def compute_lump_sum(df, initial_investment):
    first_price = df["Close"].iloc[0]
    shares = initial_investment / first_price

    lump_value = df["Close"] * shares

    return lump_value, shares


def compute_dca(df, monthly_contribution, n_months):
    monthly_period = df.index.to_period("M")

    purchase_dates = (
        df.groupby(monthly_period)
          .head(1)
          .index[:n_months]
    )

    if len(purchase_dates) < n_months:
        raise ValueError(
            f"Only {len(purchase_dates)} purchase months found, "
            f"but {n_months} were required."
        )

    is_purchase_day = df.index.isin(purchase_dates)

    shares_bought = np.where(
        is_purchase_day,
        monthly_contribution / df["Close"].to_numpy(),
        0.0,
    )

    shares_bought = pd.Series(
        shares_bought,
        index=df.index,
        name="Shares_Bought",
    )

    cumulative_shares = shares_bought.cumsum()

    dca_value = cumulative_shares * df["Close"]

    invested_today = np.where(
        is_purchase_day,
        monthly_contribution,
        0.0,
    )

    invested_today = pd.Series(
        invested_today,
        index=df.index,
        name="Invested_Today",
    )

    cumulative_invested = invested_today.cumsum()

    return (
        dca_value,
        cumulative_invested,
        shares_bought,
        purchase_dates,
    )


def xnpv(rate, cash_flows):
    dates = pd.to_datetime(cash_flows.index)
    values = cash_flows.to_numpy(dtype=float)

    days = (dates - dates[0]).days.to_numpy()

    return np.sum(
        values / (1 + rate) ** (days / 365.25)
    )


def xirr(cash_flows):
    cash_flows = cash_flows.dropna().astype(float)

    if not (cash_flows < 0).any():
        return np.nan

    if not (cash_flows > 0).any():
        return np.nan

    def objective(rate):
        return xnpv(rate, cash_flows)

    lower_bound = -0.9999
    upper_bound = 1.0

    while objective(upper_bound) > 0 and upper_bound < 1_000_000:
        upper_bound *= 2

    try:
        result = brentq(
            objective,
            lower_bound,
            upper_bound,
        )
        return result

    except ValueError:
        return np.nan


def compute_cash_flow_adjusted_returns(
    portfolio_value,
    invested_today,
):
    previous_value = portfolio_value.shift(1)

    denominator = previous_value + invested_today

    adjusted_returns = portfolio_value / denominator - 1

    adjusted_returns.iloc[0] = np.nan

    return adjusted_returns


def maximum_drawdown_from_returns(returns):
    returns = returns.fillna(0.0)

    wealth_index = (1 + returns).cumprod()

    running_max = wealth_index.cummax()

    drawdown = wealth_index / running_max - 1

    return drawdown.min()


def maximum_drawdown_from_values(values):
    running_max = values.cummax()

    drawdown = values / running_max - 1

    return drawdown.min()


def calculate_lump_sum_metrics(
    df,
    lump_value,
    initial_investment,
):
    start_date = df.index[0]
    end_date = df.index[-1]

    cash_flows = pd.Series(
        [-initial_investment, lump_value.iloc[-1]],
        index=[start_date, end_date],
        dtype=float,
    )

    annualized_return = xirr(cash_flows)

    daily_returns = lump_value.pct_change().dropna()

    volatility = (
        daily_returns.std() * np.sqrt(252)
    )

    max_drawdown = maximum_drawdown_from_values(lump_value)

    final_value = lump_value.iloc[-1]

    total_return = (
        final_value / initial_investment
    ) - 1

    return {
        "Strategy": "Lump-Sum",
        "Invested": initial_investment,
        "Final Value": final_value,
        "Profit": final_value - initial_investment,
        "Total Return (%)": total_return * 100,
        "Annualized Return (%)": annualized_return * 100,
        "Volatility (%)": volatility * 100,
        "Max Drawdown (%)": max_drawdown * 100,
    }


def calculate_dca_metrics(
    df,
    dca_value,
    cumulative_invested,
    invested_today,
    purchase_dates,
):
    final_value = dca_value.iloc[-1]
    total_invested = cumulative_invested.iloc[-1]

    dca_cash_flows = pd.Series(
        0.0,
        index=df.index,
    )

    dca_cash_flows.loc[purchase_dates] = (
        -invested_today.loc[purchase_dates]
    )

    dca_cash_flows.iloc[-1] += final_value

    annualized_return = xirr(dca_cash_flows)

    adjusted_daily_returns = (
        compute_cash_flow_adjusted_returns(
            dca_value,
            invested_today,
        )
    )

    adjusted_returns_clean = (
        adjusted_daily_returns.dropna()
    )

    volatility = (
        adjusted_returns_clean.std() * np.sqrt(252)
    )

    max_drawdown = maximum_drawdown_from_returns(
        adjusted_daily_returns
    )

    total_return = (
        final_value / total_invested
    ) - 1

    return {
        "Strategy": "DCA",
        "Invested": total_invested,
        "Final Value": final_value,
        "Profit": final_value - total_invested,
        "Total Return (%)": total_return * 100,
        "Annualized Return (%)": annualized_return * 100,
        "Volatility (%)": volatility * 100,
        "Max Drawdown (%)": max_drawdown * 100,
    }


def print_metrics(metrics):
    print(f"\n{metrics['Strategy']}")

    print(
        f"  Invested:             "
        f"${metrics['Invested']:,.2f}"
    )

    print(
        f"  Final Value:          "
        f"${metrics['Final Value']:,.2f}"
    )

    print(
        f"  Profit:               "
        f"${metrics['Profit']:,.2f}"
    )

    print(
        f"  Total Return:         "
        f"{metrics['Total Return (%)']:.2f}%"
    )

    print(
        f"  Annualized Return:    "
        f"{metrics['Annualized Return (%)']:.2f}%"
    )

    print(
        f"  Volatility:           "
        f"{metrics['Volatility (%)']:.2f}%"
    )

    print(
        f"  Max Drawdown:         "
        f"{metrics['Max Drawdown (%)']:.2f}%"
    )


results = {}
summary_rows = []


for scenario in SCENARIOS:

    label = scenario["label"]

    print("\n" + "=" * 70)
    print(f"SCENARIO: {label}")
    print("=" * 70)

    try:
        df = fetch_price_data(
            ticker=scenario["ticker"],
            start=scenario["start"],
            end=scenario["end"],
        )

    except Exception as error:
        print(
            f"Error while downloading data: {error}",
            file=sys.stderr,
        )
        continue

    monthly_contribution = (
        INITIAL_INVESTMENT / N_MONTHS
    )

    (
        df["Lump_Sum_Value"],
        lump_shares,
    ) = compute_lump_sum(
        df,
        INITIAL_INVESTMENT,
    )

    (
        df["DCA_Value"],
        df["DCA_Invested"],
        df["Shares_Bought"],
        purchase_dates,
    ) = compute_dca(
        df,
        monthly_contribution,
        N_MONTHS,
    )

    df["Invested_Today"] = np.where(
        df.index.isin(purchase_dates),
        monthly_contribution,
        0.0,
    )

    lump_metrics = calculate_lump_sum_metrics(
        df,
        df["Lump_Sum_Value"],
        INITIAL_INVESTMENT,
    )

    dca_metrics = calculate_dca_metrics(
        df,
        df["DCA_Value"],
        df["DCA_Invested"],
        df["Invested_Today"],
        purchase_dates,
    )

    print_metrics(lump_metrics)
    print_metrics(dca_metrics)

    if (
        lump_metrics["Final Value"]
        > dca_metrics["Final Value"]
    ):
        winner = "Lump-Sum"
    else:
        winner = "DCA"

    results[label] = {
        "data": df,
        "lump_metrics": lump_metrics,
        "dca_metrics": dca_metrics,
        "purchase_dates": purchase_dates,
    }

    summary_rows.append(
        {
            "Scenario": label,

            "Lump-Sum Final Value": round(
                lump_metrics["Final Value"],
                2,
            ),

            "DCA Final Value": round(
                dca_metrics["Final Value"],
                2,
            ),

            "Lump-Sum Profit": round(
                lump_metrics["Profit"],
                2,
            ),

            "DCA Profit": round(
                dca_metrics["Profit"],
                2,
            ),

            "Lump-Sum XIRR (%)": round(
                lump_metrics["Annualized Return (%)"],
                2,
            ),

            "DCA XIRR (%)": round(
                dca_metrics["Annualized Return (%)"],
                2,
            ),

            "Lump-Sum Volatility (%)": round(
                lump_metrics["Volatility (%)"],
                2,
            ),

            "DCA Volatility (%)": round(
                dca_metrics["Volatility (%)"],
                2,
            ),

            "Lump-Sum Max Drawdown (%)": round(
                lump_metrics["Max Drawdown (%)"],
                2,
            ),

            "DCA Max Drawdown (%)": round(
                dca_metrics["Max Drawdown (%)"],
                2,
            ),

            "Winner": winner,
        }
    )

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=df.index,
            y=df["Lump_Sum_Value"],
            mode="lines",
            name="Lump-Sum Portfolio",
            line=dict(
                color="firebrick",
                width=2,
            ),
        )
    )

    fig.add_trace(
        go.Scatter(
            x=df.index,
            y=df["DCA_Value"],
            mode="lines",
            name="DCA Portfolio",
            line=dict(
                color="royalblue",
                width=2,
            ),
        )
    )

    fig.add_trace(
        go.Scatter(
            x=df.index,
            y=df["DCA_Invested"],
            mode="lines",
            name="DCA Cumulative Invested",
            line=dict(
                color="gray",
                width=1.5,
                dash="dash",
            ),
        )
    )

    purchase_values = df.loc[
        purchase_dates,
        "DCA_Value",
    ]

    fig.add_trace(
        go.Scatter(
            x=purchase_dates,
            y=purchase_values,
            mode="markers",
            name="DCA Purchase Dates",
            marker=dict(
                color="black",
                size=6,
                symbol="circle",
            ),
        )
    )

    fig.update_layout(
        title=f"DCA vs Lump-Sum — {label}",
        xaxis_title="Date",
        yaxis_title="Portfolio Value ($)",
        template="plotly_white",
        hovermode="x unified",
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01,
        ),
    )

    fig.show()


print("\n" + "=" * 70)
print("SUMMARY — ALL SCENARIOS")
print("=" * 70)

summary_df = pd.DataFrame(summary_rows)

if not summary_df.empty:
    display(summary_df)

else:
    print("No valid backtest results were produced.")